export const trackList = [
  {
    title: 'Flight FM',
    src: '/Tracks/flight fm.mp3',
    img: [
      {
        src: '/TrackImages/flight-fm.jpeg',
        sizes: '96x96',
        type: 'image/png',
      },
      {
        src: '/TrackImages/flight-fm.jpeg',
        sizes: '128x128',
        type: 'image/png',
      },
      {
        src: '/TrackImages/flight-fm.jpeg',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/TrackImages/flight-fm.jpeg',
        sizes: '256x256',
        type: 'image/png',
      },
      {
        src: '/TrackImages/flight-fm.jpeg',
        sizes: '384x384',
        type: 'image/png',
      },
      {
        src: '/TrackImages/flight-fm.jpeg',
        sizes: '512x512',
        type: 'image/png',
      },
    ],
    artist: 'Joy Orbison',
    duration: '04:06',
  },
  {
    title: 'Share The Love',
    src: '/Tracks/Share The Love.mp3',
    img: [{ src: '/TrackImages/fl.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Fruity Loops',
    duration: '05:25',
  },
  {
    title: 'Alright',
    src: '/Tracks/Alright.mp3',
    img: [{ src: '/TrackImages/fl.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Fruity Loops',
    duration: '07:44',
  },
  {
    title: 'Acid Income',
    src: '/Tracks/Acid Income.mp3',
    img: [{ src: '/TrackImages/HoodAnthems.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Broosnicka',
    duration: '03:21',
  },
  {
    title: 'Flight FM',
    src: '/Tracks/flight fm.mp3',
    img: [{ src: '/TrackImages/flight-fm.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Joy Orbison',
    duration: '04:06',
  },
  {
    title: 'Share The Love',
    src: '/Tracks/Share The Love.mp3',
    img: [{ src: '/TrackImages/fl.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Fruity Loops',
    duration: '05:25',
  },
  {
    title: 'Alright',
    src: '/Tracks/Alright.mp3',
    img: [{ src: '/TrackImages/fl.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Fruity Loops',
    duration: '07:44',
  },
  {
    title: 'Acid Income',
    src: '/Tracks/Acid Income.mp3',
    img: [{ src: '/TrackImages/HoodAnthems.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Broosnicka',
    duration: '03:21',
  },
  {
    title: 'Flight FM',
    src: '/Tracks/flight fm.mp3',
    img: [{ src: '/TrackImages/flight-fm.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Joy Orbison',
    duration: '04:06',
  },
  {
    title: 'Share The Love',
    src: '/Tracks/Share The Love.mp3',
    img: [{ src: '/TrackImages/fl.jpeg', sizes: '96x96', type: 'image/jpeg' }],
    artist: 'Fruity Loops',
    duration: '05:25',
  },
];
